config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get 'pages/home', to: 'pages#home'

  resources :recipes do
    resources :comments, only: [:create]
    member do
      post 'like'
    end
  end


  get '/signup', to: 'chefs#new'
  resources :chefs, except: [:new]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :ingredients, except: [:destroy]
  
  mount ActionCable.server => '/cable'
  
  get '/chat', to: 'chatrooms#show'
  
  resources :messages, only:[:create]

end

app/views/layouts/_footer.html.erb
<footer class="page-footer font-small fixed-bottom">

  <!-- Copyright -->
  <div class="footer-copyright float-right py-3 mr-1">© 2019 Copyright: Rhonda Tinkham
  </div>
  <!-- Copyright -->

</footer>

app/views/layouts/_messages.html.erb
<div class="row mx-auto" style="width: 50%;">
  <div class="col text-center">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name %>">
        <a href="#" class="close" data-dismiss="alert">×</a>
        <%= msg %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #15982b;">

	<%= link_to "RecipeShare", root_path, class: "navbar-brand pl-5 d-flex ml-auto", id: "logo" %>

  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav mx-auto w-100">
      <li class="nav-item">
        <%= link_to "Chefs", chefs_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Recipes", recipes_path, class: "nav-link" %>
      </li>
      <% if logged_in? %>
        <li class="nav-item">
          <%= link_to "ChefChat", chat_path, class: "nav-link" %>
        </li>
       <li class="nav-item">
        <%= link_to "Create Recipe", new_recipe_path,  class: "nav-link" %>
      </li>

         <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Ingredients
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item">
              <%= link_to "All Ingredients", ingredients_path,  class: "nav-link" %>
            </a>
            <% Ingredient.all.each do |ingredient| %>
              <a class="dropdown-item">
                <%= link_to ingredient.name.capitalize, ingredient_path(ingredient),  class: "nav-link" %>
              </a>
            <% end %>
            <% if logged_in? && current_chef.admin? %>
              <div role="separator" class="dropdown-divider"></div>
                <a class="dropdown-item">
                  <%= link_to "New Ingredient", new_ingredient_path,  class: "nav-link" %>
                </a>
            <% end %>
          </div>
        </li>
      <% end %>
        <ul class="nav navbar-nav ml-auto w-50 justify-content-end">

        <% if logged_in? %>

          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_chef.chefname.capitalize %>'s Profile
                 <%= "| Admin" if current_chef.admin? %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item">
              <%= link_to "View your profile", chef_path(current_chef),  class: "nav-link" %>
            </a>
            <a class="dropdown-item">
              <%= link_to "Edit your profile", edit_chef_path(current_chef),  class: "nav-link" %>
            </a>
            <div role="separator" class="dropdown-divider"></div>
            <a class="dropdown-item">
            <%= link_to "Log Out", logout_path, method: :delete,  class: "nav-link" %>
          </a>
        <% else %>
          <li class="nav-item">
            <%= link_to "Log In", login_path, class: "nav-link" %>
          </li>
        <% end %>

      </ul>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeShare</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class='container'>
      <%= yield %>
    </div>
     <%= render 'layouts/footer' %>

  </body>
</html>